[env:bw16]
platform = file://../../platform
board = bw16
framework = arduino
monitor_speed = 115200
platform_packages =
    framework-arduinorealtek-amebad @ file://../../vendor/framework-arduinorealtek-amebad-3.1.9-bundle.tar.gz
    toolchain-realtek-amebad @ file://../../vendor/toolchain-realtek-amebad-windows-1.0.1-bundle.tar.gz
    tool-realtek-amebad @ file://../../vendor/tool-realtek-amebad-windows-1.1.3-bundle.tar.gz
    platformio/tool-scons @ file://../../vendor/tool-scons-4.40801.0-bundle.tar.gz

; upload_port = COM5
